name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Install Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@15.206.72.233 << 'EOF'
          # Clone the repository
          git https://github.com/sireeshajangam/demo-python-app.git

          # Build the Docker image
          sudo docker build -t python-app .

          # Run the Docker container
          sudo docker run -d -p 80:5000 --name python-container python-app
        EOF
